#!/bin/sh

# Android SDK updater
#
# Automatically download new versions of the SDK, update files and keep track of current
# version.

update_sdk_32(){
    echo "Removing current SDK ..."
    rm -rf sdk/* 1>/dev/null 2>/dev/null
    echo "Downloading Android SDK ..."
    mkdir -p /tmp/sdk/
    curl $SDK32 > /tmp/sdk/sdk.tgz
    echo "Unzipping and updating ..."
    tar -C /tmp/sdk/ xvzf /tmp/sdk/sdk.tgz 2>/dev/null 1>/dev/null
    cp -rf /tmp/sdk/android-sdk-linux/* sdk/
    rm -rf /tmp/sdk
    echo "$SDK32_VER" > sdk/version
}

# Retrieve SDK URLS
echo "Checking SDK versions ..."
SDK_INDEX=$(curl -s "https://developer.android.com/sdk/index.html")

# Check versions
SDK_CURVER=$(cat sdk/version)

echo "32-bit SDK selected"
SDK32=$(echo $SDK_INDEX | sed -n 's/.*\(http:\/\/dl.google.com\/android\/android-sdk_r[0-9]\+\.[0-9]\+\.[0-9]\+-linux\.tgz\).*/\1/p')
SDK32_VER=$(echo $SDK32 | sed -n 's/^.*-sdk_r\([0-9]\+\)\.[0-9]\+.[0-9]\+-linux\.tgz$/\1/p')

if [ $SDK32_VER -ne $SDK_CURVER ]; then
    echo "New version of Android SDK found, updating ..."
    update_sdk
    echo "Android SDK up-to-date."
else
    echo "Android SDK up-to-date, nothing to do."
fi
